changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: "🚀 Features"
      labels:
        - enhancement
        - feature
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
    - title: "⚡ Performance"
      labels:
        - performance
    - title: "♻️ Refactoring"
      labels:
        - refactor
    - title: "📝 Documentation"
      labels:
        - documentation
    - title: "🔧 Maintenance"
      labels:
        - chore
        - ci
        - dependencies
    - title: "📦 Other Changes"
      labels:
        - "*"
